FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    dnsmasq \
    dsniff \
    iptables \
    iproute2 \
    procps \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

COPY dns_redirect_entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
